# Generated by Django 4.2.6 on 2023-10-18 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=datetime.datetime(2023, 10, 18, 5, 10, 12, 729880, tzinfo=datetime.timezone.utc), upload_to='gallery'),
            preserve_default=False,
        ),
    ]
